 2022-07-14 08:20:17,048 - INFO - [main] Current date: 2022-07-14
 2022-07-14 08:20:17,048 - INFO - [main] New CSV doesn't needed! Starting polling!
 2022-07-14 08:20:17,066 - INFO - Started polling.
 2022-07-14 08:20:17,079 - ERROR - Infinity polling exception: Bot token is not defined
 2022-07-14 08:20:17,086 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 570, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 621, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 695, in __threaded_polling
    raise e
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 650, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 360, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\__init__.py", line 338, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\apihelper.py", line 324, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\svsergeev\sm_bot\sm_bot_venv\lib\site-packages\telebot\apihelper.py", line 80, in _make_request
    raise Exception('Bot token is not defined')
Exception: Bot token is not defined

